services:
    #
    # Common Form Types
    #
    mapbender.form_type.html:
            class: Mapbender\CoreBundle\Form\Type\HtmlFormType
            arguments:
                - '@mapbender.constraint.html'
                - '@mapbender.constraint.twig'
            tags:
                - { name: form.type }
