parameters:
    applications: {}

    mapbender.branding.name: Mapbender
    mapbender.version: 3.1.0.2
    mapbender.branding.logo: bundles/mapbendercore/image/logo_mb.png
    # These should all remain empty here, they are just for IDE search results.
    # Customize these in your parameters.yml.
    # The name will show up in page titles; the version will show in your backend;
    # the logo will display on your login page, the backend again, and some of the application templates.
    branding.project_name: ~
    branding.project_version: ~
    branding.logo: ~                # web-relative path

    # Sitelinks displayed below login box and backend content
    # Should be a list of items each with keys 'link' and 'text'
    mapbender.sitelinks: []
