services:
  mapbender2_geometryprovider:
    class: OwsProxy3\CoreBundle\GeometryProvider\Mapbender2GeometryProvider
    arguments: [ "@service_container" ]

parameters:
    applications:
        mapbender_user:
            title: Mapbender User Demo Map: Europe
            description: "Fullscreen style, Simple map showing WMS use."
            published: true
            template:  Mapbender\CoreBundle\Template\Fullscreen
            layersets:
                main:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: http://osm.wheregroup.com/cgi-bin/osm_basic.xml
                        layers:
                            - { name: OSM_Basic,    title : User,  visible: true }
                        info_format: text/html
                        baselayer: false
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 85
                        legendgraphic: http://wms.wheregroup.com/cgi-bin/mapserv?map=/data/umn/mapbender_user/mapbender_user.map&REQUEST=GetLegendGraphic&VERSION=1.1.1&SERVICE=WMS
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Open Street Map
                        url: http://osm.omniscale.net/proxy/service?
                        layers:
                            - { name: osm, title: Open Street Map WMS Omniscale }
                        tiled: false
                        visible: true
                        baselayer: false
                overview:
                    osm_overview:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Open Street Map
                        url: http://osm.omniscale.net/proxy/service?
                        layers:
                            - { name: osm, title: Open Street Map WMS }
                        tiled: false
                        visible: true
                        baselayer: true
            elements:
                toolbar:
                    about:
                        title: About
                        tooltip: About
                        label: true
                        class: Mapbender\CoreBundle\Element\AboutDialog
                    gps-button:
                        title: GPS
                        tooltip: GPS
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: true
                        target: printclient
                        action: open
                    print-button:
                        title: Print
                        tooltip: Print PDF
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconPrint
                        label: true
                        target: printclient
                        action: open
                    fi:
                        title: Feature Info
                        tooltip: Feature Info
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconFeatureInfo
                        label: true
                    legend:
                        title: Legend
                        tooltip: Legend
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconLegend
                        label: true
                    wms:
                        title: Wms Loader
                        tooltip: Wms
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconWms
                        label: true
                    search:
                        title: Search
                        tooltip: Search
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconSearch
                        label: true