services:
    # Use the four following services to enable cookie-less logins
    #session.storage.native:
    #    # Enabled session id transport via GET parameter
    #    class: Mapbender\Component\UrlSessionStorage
    #    arguments: [%session.storage.options%, @service_container]
    #security.authentication.form_entry_point:
    #    # Makes sure the session id is passed to the login form
    #    class: Mapbender\Component\UrlSessionFormEntryPoint
    #    public: false
    #    abstract: true
    #    arguments: [@http_kernel]
    #security.authentication.success_handler:
    #    # Updates session id GET parameter after login
    #    class: Mapbender\Component\UrlSessionLoginHandler
    #    public: false
    #    arguments: []
    #urlsession.redirect.listener:
    #    # Intercept redirects and update Location header with session id
    #    class: Mapbender\Component\UrlSessionRedirectListener
    #    arguments: [ @service_container ]
    #    tags:
    #        - { name: kernel.event_listener, event: kernel.response }
  mapbender2_geometryprovider:
    class: OwsProxy3\CoreBundle\GeometryProvider\Mapbender2GeometryProvider
    arguments: [ "@service_container" ]
#  owsproxy.spatialsecurity.listener:
#    class: OwsProxy3\CoreBundle\EventListener\SpatialSecurityListener
#    arguments: [ @service_container ]
#    tags:
#      - { name: kernel.event_listener, event: owsproxy_before_proxy, method: beforeProxyEvent }

parameters:
    #sensio_framework_extra.converter.doctrine.class: "Mapbender\Component\CustomDoctrineParamConverter"
    applications:
        mapbender_user:
            title: Mapbender User Demo Map
            description: "Simple map showing WMS use."
            published: true
            #roles: [ROLE_USER]
            template:  Mapbender\CoreBundle\Template\Fullscreen
            layersets:
                main:
                    ne2:
                        class: Mapbender\WmsBundle\WmsLayer
                        title: Natural Earth
                        url: http://www.catais.org/geoserver/wms?SERVICE=WMS
                        layers:
                            - { name: 'ne2:ne2', title: 'Natural Earth 2'}
                        tiled: true
                    osm_roads:
                        class: Mapbender\WmsBundle\WmsLayer
                        title: OpenStreetMap Roads
                        url: http://osm.omniscale.net/proxy/service?
                        layers:
                            - { name: osm_roads, title: OpenStreetMap WMS }
                        tiled: false
                        baselayer: false
                    mapbender_users:
                        class: Mapbender\WmsBundle\WmsLayer
                        title: Mapbender Users
                        url: http://wms.wheregroup.com/cgi-bin/mapserv?map=/data/umn/mapbender_user/mapbender_user.map
                        layers:
                            - { name: Mapbender_User,    title : User,  visible: true }
                            - { name: Mapbender_Names,   title : Name,   visible: true, queryable: true }
                        queryLayers: [Mapbender_Names]
                        queryFormat: text/html
                        baselayer: false
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 85
                overview:
                    demis:
                        class: Mapbender\WmsBundle\WmsLayer
                        title: Demis World Map
                        url: http://www.catais.org/geoserver/wms?SERVICE=WMS
                        layers:
                            - { name: 'ne2:ne2', title: 'Natural Earth 2'}
            elements:
                top:
                    #mapclick:
                    #    title: Map Click
                    #    class: Acme\DemoBundle\Element\MapClick
                    #    label: true
                    #    group: maptools
                    #    target: map
                    #mapbox:
                    #    title: Map Box
                    #    class: Acme\DemoBundle\Element\MapBox
                    #    group: maptools
                    #    target: map
                    toc-button:
                        title: TOC
                        class: Mapbender\CoreBundle\Element\Button
                        target: toc
                        action: open
                    about:
                        title: About
                        class: Mapbender\CoreBundle\Element\AboutDialog
                    fi:
                        title: FeatureInfo
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        icon: featureinfo
                        label: false
                        target: map
                content:
                    map:
                        title: Main Map
                        class: Mapbender\CoreBundle\Element\Map
                        layerset: main
                        srs: EPSG:4326
                        units: degrees
                        extents:
                            start: [-43.313833377731, 33.006761223615, 65.104961268907, 59.198710149963]
                            max: [-180,-90,180,90]
                        scales: [25000000, 10000000,5000000,1000000,500000]
                        maxResolution: 'auto'
                        #overview:
                        #    layerset: overview
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        position: ['1em', '4em']
                    toc:
                        title: Table of Contents
                        class: Mapbender\CoreBundle\Element\Toc
                        target: map
                        autoOpen: false
                footer:
                    coordinates:
                        class: Mapbender\CoreBundle\Element\CoordinatesDisplay
                        target: map

