# Per default, the application list is the start page. You may change that.
_mapbender_start:
    pattern: "/"
    defaults: { _controller: MapbenderCoreBundle:Application:list}

_mapbender_application:
    resource: "@MapbenderCoreBundle/Controller/ApplicationController.php"
    type: annotation

_mapbender_proxy:
    resource: "@MapbenderCoreBundle/Controller/ProxyController.php"
    type: annotation

_mapbender_user:
    resource: "@MapbenderCoreBundle/Controller/UserController.php"
    type: annotation

_mapbender_wms:
    resource: "@MapbenderWmsBundle/Controller/WMSController.php"
    type: annotation
    prefix: /wms

_mapbender_wmslayer:
    resource: "@MapbenderWmsBundle/Controller/WMSLayerController.php"
    type: annotation
    prefix: /wms

