# Per default, the application list is the start page. You may change that.

mapbender_start:
    pattern: "/"
    defaults: { _controller: MapbenderCoreBundle:Welcome:list}

mapbender_corebundle:
    resource: "@MapbenderCoreBundle/Controller/"
    type: annotation

#_mapbender_wmsbundle:
#    resource: "@MapbenderWmsBundle/Controller/"
#    type: annotation

mapbender_managerbundle:
    resource: "@MapbenderManagerBundle/Controller"
    prefix: "/manager"

_mapbender_wmsbundle:
    resource: "@OwsProxy3CoreBundle/Controller/"
    prefix: "/owsproxy"
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

