# Per default, the application list is the start page. You may change that.
_mapbender_start:
    pattern: "/"
    defaults: { _controller: MapbenderCoreBundle:Application:list}

_mapbender_corebundle:
    resource: "@MapbenderCoreBundle/Controller/"
    type: annotation

_mapbender_wmsbundle:
    resource: "@MapbenderWmsBundle/Controller/"
    type: annotation

_mapbender_managerbundle:
    resource: "@MapbenderManagerBundle/Controller"
    prefix: "/manager"
    type: annotation
