# Per default, the application list is the start page. You may change that.

mapbender_start:
    pattern: "/"
    defaults: { _controller: MapbenderCoreBundle:Welcome:list}

mapbender_corebundle:
    resource: "@MapbenderCoreBundle/Controller/"
    type: annotation

#mapbender_wmsbundle:
#    resource: "@MapbenderWmsBundle/Controller/"
#    type: annotation

#fom_managerbundle:
#    resource: "@FOMManagerBundle/Controller"
#    type: annotation

fom_userbundle_login:
    resource: "@FOMUserBundle/Controller/LoginController.php"
    type: annotation

fom_userbundle_registration:
    resource: "@FOMUserBundle/Controller/RegistrationController.php"
    type: annotation

fom_userbundle_password:
    resource: "@FOMUserBundle/Controller/PasswordController.php"
    type: annotation

ows_corebundle:
    resource: "@OwsProxy3CoreBundle/Controller/"
    prefix: "/owsproxy"
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

