security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: user, roles: [ 'ROLE_USER' ] }
                root: { password: root, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /user/login/check
                login_path: /user/login
            logout:
                path:   /user/logout
                target: /

    access_control:
        - { path: ^/user/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user,          roles: ROLE_USER }
        - { path: ^/admin,         roles: ROLE_ADMIN }
